package services

import "builder/src/models"

type Item struct {
	Armet                models.Item_Armor
	CrusaderHelm         models.Item_Armor
	ChapelDeFer          models.Item_Armor
	Doublet              models.Item_Armor
	RivetedGloves        models.Item_Armor
	OccultistPants       models.Item_Armor
	LightfootBoots       models.Item_Armor
	RadiantCloak         models.Item_Armor
	AdventurerCloak      models.Item_Armor
	BarbutaHelm          models.Item_Armor
	ArmingSword          models.Item_Weapon
	Bardiche             models.Item_Weapon
	LooseTrousers        models.Item_Armor
	FoxPendant           models.Item_Accessory
	RingOfCourage        models.Item_Accessory
	AdventurerBoots      models.Item_Armor
	ArcaneHood           models.Item_Armor
	CeremonialHeaddress  models.Item_Armor
	Chaperon             models.Item_Armor
	Coif                 models.Item_Armor
	DarkgroveHood        models.Item_Armor
	ElkwoodCrown         models.Item_Armor
	FeatheredHat         models.Item_Armor
	ForestHood           models.Item_Armor
	Gjermundbu           models.Item_Armor
	GreatHelm            models.Item_Armor
	Hounskull            models.Item_Armor
	KettleHat            models.Item_Armor
	LeatherBonnet        models.Item_Armor
	LeatherCap           models.Item_Armor
	NormanNasalHelm      models.Item_Armor
	OpenSallet           models.Item_Armor
	RangerHood           models.Item_Armor
	RogueCowl            models.Item_Armor
	Sallet               models.Item_Armor
	ShadowHood           models.Item_Armor
	ShadowMask           models.Item_Armor
	Spangenhelm          models.Item_Armor
	StrawHat             models.Item_Armor
	Topfhelm             models.Item_Armor
	VikingHelm           models.Item_Armor
	OccultistHood        models.Item_Armor
	AdventurerTunic      models.Item_Armor
	ArcaneGrab           models.Item_Armor
	ArcaneGloves         models.Item_Armor
	BardicPants          models.Item_Armor
	BloodwovenGloves     models.Item_Armor
	ChampionArmor        models.Item_Armor
	CrusaderArmor        models.Item_Armor
	BloodwovenRobe       models.Item_Armor
	BuckledBoots         models.Item_Armor
	ButtonedBoots        models.Item_Armor
	ButtonedLeggings     models.Item_Armor
	ClothPants           models.Item_Armor
	CuffedBoots          models.Item_Armor
	DarkCuirass          models.Item_Armor
	DarkgroveRobe        models.Item_Armor
	DarkleafBoots        models.Item_Armor
	DarkLeatherLeggings  models.Item_Armor
	DarkPlateArmor       models.Item_Armor
	DashingBoots         models.Item_Armor
	DreadHood            models.Item_Armor
	ElkwoodGloves        models.Item_Armor
	FineCuirass          models.Item_Armor
	ForestBoots          models.Item_Armor
	Frock                models.Item_Armor
	GlovesOfUtility      models.Item_Armor
	GrandBrigandine      models.Item_Armor
	WandererAttire       models.Item_Armor
	WatchmanCloak        models.Item_Armor
	WizardHat            models.Item_Armor
	WizardShoes          models.Item_Armor
	HeavyBoots           models.Item_Armor
	HeavyGambeson        models.Item_Armor
	HeavyGauntlets       models.Item_Armor
	HeavyLeggings        models.Item_Armor
	HeavyLeatherLeggings models.Item_Armor
	LacedTurnshoe        models.Item_Armor
	LeatherGloves        models.Item_Armor
	LeatherLeggings      models.Item_Armor
	LightAketon          models.Item_Armor
	LightGauntlets       models.Item_Armor
	LowBoots             models.Item_Armor
	MarauderOutfit       models.Item_Armor
	MercurialCloak       models.Item_Armor
	MysticGloves         models.Item_Armor
	MysticVestments      models.Item_Armor
	NorthernFullTunic    models.Item_Armor
	OccultistRobe        models.Item_Armor
	OccultistTunic       models.Item_Armor
	OldShoes             models.Item_Armor
	Pourpoint            models.Item_Armor
	TemplarArmor         models.Item_Armor
	BadgerPendant        models.Item_Accessory
	BearPendant          models.Item_Accessory
	FrostAmulet          models.Item_Accessory
	MonkeyPendant        models.Item_Accessory
	NecklaceOfPeace      models.Item_Accessory
	OwlPendant           models.Item_Accessory
	OxPendant            models.Item_Accessory
	PhoenixChoker        models.Item_Accessory
	RatPendant           models.Item_Accessory
	TorqOfSoul           models.Item_Accessory
	WindLocket           models.Item_Accessory
	FangsOfDeathNecklace models.Item_Accessory
	RingOfFinesse        models.Item_Accessory
	RingOfQuickness      models.Item_Accessory
	RingOfSurvival       models.Item_Accessory
	RingOfVitality       models.Item_Accessory
	RingOfWisdom         models.Item_Accessory
	RingOfResolve        models.Item_Accessory
	TatteredCloak        models.Item_Armor
	SplendidCloak        models.Item_Armor
	OccultistBoots       models.Item_Armor
	PlateBoots           models.Item_Armor
	VisoredSallet        models.Item_Armor
	VisoredBarbutaHelm   models.Item_Armor
	CastillonDagger      models.Item_Weapon
	Buckler              models.Item_Weapon
	CeremonialStaff      models.Item_Weapon
	Club                 models.Item_Weapon
	Crossbow             models.Item_Weapon
	CrystalBall          models.Item_Weapon
	CrystalSword         models.Item_Weapon
	DoubleAxe            models.Item_Weapon
	Falchion             models.Item_Weapon
	FellinAxe            models.Item_Weapon
	FranciscaAxe         models.Item_Weapon
	Hatchet              models.Item_Weapon
	Halberd              models.Item_Weapon
	HandCrossbow         models.Item_Weapon
	HeaterShield         models.Item_Weapon
	HorsemanAxe          models.Item_Weapon
	KrisDagger           models.Item_Weapon
	LaternShield         models.Item_Weapon
	Longbow              models.Item_Weapon
	Longsword            models.Item_Weapon
	MagicStaff           models.Item_Weapon
	MorningStar          models.Item_Weapon
	Pavise               models.Item_Weapon
	Quarterstaff         models.Item_Weapon
	Rapier               models.Item_Weapon
	RecurveBow           models.Item_Weapon
	RoundShield          models.Item_Weapon
	Spear                models.Item_Weapon
	Spellbook            models.Item_Weapon
	StilletoDagger       models.Item_Weapon
	SurvivalBow          models.Item_Weapon
	ThrowingKnife        models.Item_Weapon
	VikingSword          models.Item_Weapon
	WarHammer            models.Item_Weapon
	WarMaul              models.Item_Weapon
	WindlassCrossbow     models.Item_Weapon
	Zweihander           models.Item_Weapon
	PaddedTunic          models.Item_Armor
}

type List_Items struct {
	ItemsArmor     []*models.Item_Armor
	ItemsWeapon    []*models.Item_Weapon
	ItemsAccessory []*models.Item_Accessory
}
