package controllers

import (
	"builder/src/models"
	"builder/src/services"
)

func CreateItemArmor(itemfile string) models.Item_Armor {
	var item_create models.Item_Armor // &item to create
	readJSON(itemfile, &item_create)
	return item_create
}

func CreateItemWeapon(itemfile string) models.Item_Weapon {
	var item_create models.Item_Weapon // &item to create
	readJSON(itemfile, &item_create)
	return item_create
}

func CreateItemAccessory(itemfile string) models.Item_Accessory {
	var item_create models.Item_Accessory // &item to create
	readJSON(itemfile, &item_create)
	return item_create
}

var item = services.Item{
	Armet:                CreateItemArmor("./data/Armet.json"),
	BarbutaHelm:          CreateItemArmor("./data/BarbutaHelm.json"),
	ChapelDeFer:          CreateItemArmor("./data/ChapelDeFer.json"),
	CrusaderHelm:         CreateItemArmor("./data/CrusaderHelm.json"),
	Doublet:              CreateItemArmor("./data/Doublet.json"),
	RivetedGloves:        CreateItemArmor("./data/RivetedGloves.json"),
	OccultistPants:       CreateItemArmor("./data/OccultistPants.json"),
	LooseTrousers:        CreateItemArmor("./data/LooseTrousers.json"),
	LightfootBoots:       CreateItemArmor("./data/LightfootBoots.json"),
	RadiantCloak:         CreateItemArmor("./data/RadiantCloak.json"),
	AdventurerCloak:      CreateItemArmor("./data/AdventurerCloak.json"),
	ArmingSword:          CreateItemWeapon("./data/ArmingSword.json"),
	Bardiche:             CreateItemWeapon("./data/Bardiche.json"),
	FoxPendant:           CreateItemAccessory("./data/FoxPendant.json"),
	RingOfCourage:        CreateItemAccessory("./data/RingOfCourage.json"),
	AdventurerBoots:      CreateItemArmor("./data/AdventurerBoots.json"),
	ArcaneHood:           CreateItemArmor("./data/ArcaneHood.json"),
	CeremonialHeaddress:  CreateItemArmor("./data/CeremonialHeaddress.json"),
	Chaperon:             CreateItemArmor("./data/Chaperon.json"),
	Coif:                 CreateItemArmor("./data/Coif.json"),
	DarkgroveHood:        CreateItemArmor("./data/DarkgroveHood.json"),
	ElkwoodCrown:         CreateItemArmor("./data/ElkwoodCrown.json"),
	FeatheredHat:         CreateItemArmor("./data/FeatheredHat.json"),
	ForestHood:           CreateItemArmor("./data/ForestHood.json"),
	Gjermundbu:           CreateItemArmor("./data/Gjermundbu.json"),
	GreatHelm:            CreateItemArmor("./data/GreatHelm.json"),
	Hounskull:            CreateItemArmor("./data/Hounskull.json"),
	KettleHat:            CreateItemArmor("./data/KettleHat.json"),
	LeatherBonnet:        CreateItemArmor("./data/LeatherBonnet.json"),
	LeatherCap:           CreateItemArmor("./data/LeatherCap.json"),
	NormanNasalHelm:      CreateItemArmor("./data/NormanNasalHelm.json"),
	OpenSallet:           CreateItemArmor("./data/OpenSallet.json"),
	RangerHood:           CreateItemArmor("./data/RangerHood.json"),
	RogueCowl:            CreateItemArmor("./data/RogueCowl.json"),
	Sallet:               CreateItemArmor("./data/Sallet.json"),
	ShadowHood:           CreateItemArmor("./data/ShadowHood.json"),
	ShadowMask:           CreateItemArmor("./data/ShadowMask.json"),
	Spangenhelm:          CreateItemArmor("./data/Spangenhelm.json"),
	StrawHat:             CreateItemArmor("./data/StrawHat.json"),
	Topfhelm:             CreateItemArmor("./data/Topfhelm.json"),
	VikingHelm:           CreateItemArmor("./data/VikingHelm.json"),
	OccultistHood:        CreateItemArmor("./data/OccultistHood.json"),
	AdventurerTunic:      CreateItemArmor("./data/AdventurerTunic.json"),
	ArcaneGrab:           CreateItemArmor("./data/ArcaneGrab.json"),
	ArcaneGloves:         CreateItemArmor("./data/ArcaneGloves.json"),
	BardicPants:          CreateItemArmor("./data/BardicPants.json"),
	BloodwovenGloves:     CreateItemArmor("./data/BloodwovenGloves.json"),
	ChampionArmor:        CreateItemArmor("./data/ChampionArmor.json"),
	CrusaderArmor:        CreateItemArmor("./data/CrusaderArmor.json"),
	BloodwovenRobe:       CreateItemArmor("./data/BloodwovenRobe.json"),
	BuckledBoots:         CreateItemArmor("./data/BuckledBoots.json"),
	ButtonedBoots:        CreateItemArmor("./data/ButtonedBoots.json"),
	ButtonedLeggings:     CreateItemArmor("./data/ButtonedLeggings.json"),
	ClothPants:           CreateItemArmor("./data/ClothPants.json"),
	CuffedBoots:          CreateItemArmor("./data/CuffedBoots.json"),
	DarkCuirass:          CreateItemArmor("./data/DarkCuirass.json"),
	DarkgroveRobe:        CreateItemArmor("./data/DarkgroveRobe.json"),
	DarkleafBoots:        CreateItemArmor("./data/DarkleafBoots.json"),
	DarkLeatherLeggings:  CreateItemArmor("./data/DarkLeatherLeggings.json"),
	DarkPlateArmor:       CreateItemArmor("./data/DarkPlateArmor.json"),
	DashingBoots:         CreateItemArmor("./data/DashingBoots.json"),
	DreadHood:            CreateItemArmor("./data/DreadHood.json"),
	ElkwoodGloves:        CreateItemArmor("./data/ElkwoodGloves.json"),
	FineCuirass:          CreateItemArmor("./data/FineCuirass.json"),
	ForestBoots:          CreateItemArmor("./data/ForestBoots.json"),
	Frock:                CreateItemArmor("./data/Frock.json"),
	GlovesOfUtility:      CreateItemArmor("./data/GlovesOfUtility.json"),
	GrandBrigandine:      CreateItemArmor("./data/GrandBrigandine.json"),
	WandererAttire:       CreateItemArmor("./data/WandererAttire.json"),
	WatchmanCloak:        CreateItemArmor("./data/WatchmanCloak.json"),
	WizardHat:            CreateItemArmor("./data/WizardHat.json"),
	WizardShoes:          CreateItemArmor("./data/WizardShoes.json"),
	HeavyBoots:           CreateItemArmor("./data/HeavyBoots.json"),
	HeavyGambeson:        CreateItemArmor("./data/HeavyGambeson.json"),
	HeavyGauntlets:       CreateItemArmor("./data/HeavyGauntlets.json"),
	HeavyLeggings:        CreateItemArmor("./data/HeavyLeggings.json"),
	HeavyLeatherLeggings: CreateItemArmor("./data/HeavyLeatherLeggings.json"),
	LacedTurnshoe:        CreateItemArmor("./data/LacedTurnshoe.json"),
	LeatherGloves:        CreateItemArmor("./data/LeatherGloves.json"),
	LeatherLeggings:      CreateItemArmor("./data/LeatherLeggings.json"),
	LightAketon:          CreateItemArmor("./data/LightAketon.json"),
	LightGauntlets:       CreateItemArmor("./data/LightGauntlets.json"),
	LowBoots:             CreateItemArmor("./data/LowBoots.json"),
	MarauderOutfit:       CreateItemArmor("./data/MarauderOutfit.json"),
	MercurialCloak:       CreateItemArmor("./data/MercurialCloak.json"),
	MysticGloves:         CreateItemArmor("./data/MysticGloves.json"),
	MysticVestments:      CreateItemArmor("./data/MysticVestments.json"),
	NorthernFullTunic:    CreateItemArmor("./data/NorthernFullTunic.json"),
	OccultistRobe:        CreateItemArmor("./data/OccultistRobe.json"),
	OccultistTunic:       CreateItemArmor("./data/OccultistTunic.json"),
	OldShoes:             CreateItemArmor("./data/OldShoes.json"),
	Pourpoint:            CreateItemArmor("./data/Pourpoint.json"),
	TemplarArmor:         CreateItemArmor("./data/TemplarArmor.json"),
	BadgerPendant:        CreateItemAccessory("./data/BadgerPendant.json"),
	BearPendant:          CreateItemAccessory("./data/BearPendant.json"),
	FrostAmulet:          CreateItemAccessory("./data/FrostAmulet.json"),
	MonkeyPendant:        CreateItemAccessory("./data/MonkeyPendant.json"),
	NecklaceOfPeace:      CreateItemAccessory("./data/NecklaceOfPeace.json"),
	OwlPendant:           CreateItemAccessory("./data/OwlPendant.json"),
	OxPendant:            CreateItemAccessory("./data/OxPendant.json"),
	PhoenixChoker:        CreateItemAccessory("./data/PhoenixChoker.json"),
	RatPendant:           CreateItemAccessory("./data/RatPendant.json"),
	TorqOfSoul:           CreateItemAccessory("./data/TorqOfSoul.json"),
	WindLocket:           CreateItemAccessory("./data/WindLocket.json"),
	FangsOfDeathNecklace: CreateItemAccessory("./data/FangsOfDeathNecklace.json"),
	RingOfFinesse:        CreateItemAccessory("./data/RingOfFinesse.json"),
	RingOfQuickness:      CreateItemAccessory("./data/RingOfQuickness.json"),
	RingOfSurvival:       CreateItemAccessory("./data/RingOfSurvival.json"),
	RingOfVitality:       CreateItemAccessory("./data/RingOfVitality.json"),
	RingOfWisdom:         CreateItemAccessory("./data/RingOfWisdom.json"),
	RingOfResolve:        CreateItemAccessory("./data/RingOfResolve.json"),
	TatteredCloak:        CreateItemArmor("./data/TatteredCloak.json"),
	SplendidCloak:        CreateItemArmor("./data/SplendidCloak.json"),
	OccultistBoots:       CreateItemArmor("./data/OccultistBoots.json"),
	PlateBoots:           CreateItemArmor("./data/PlateBoots.json"),
	VisoredSallet:        CreateItemArmor("./data/VisoredSallet.json"),
	VisoredBarbutaHelm:   CreateItemArmor("./data/VisoredBarbutaHelm.json"),
	CastillonDagger:      CreateItemWeapon("./data/CastillonDagger.json"),
	Buckler:              CreateItemWeapon("./data/Buckler.json"),
	CeremonialStaff:      CreateItemWeapon("./data/CeremonialStaff.json"),
	Club:                 CreateItemWeapon("./data/Club.json"),
	Crossbow:             CreateItemWeapon("./data/Crossbow.json"),
	CrystalBall:          CreateItemWeapon("./data/CrystalBall.json"),
	CrystalSword:         CreateItemWeapon("./data/CrystalSword.json"),
	DoubleAxe:            CreateItemWeapon("./data/DoubleAxe.json"),
	Falchion:             CreateItemWeapon("./data/Falchion.json"),
	FellinAxe:            CreateItemWeapon("./data/FellinAxe.json"),
	FranciscaAxe:         CreateItemWeapon("./data/FranciscaAxe.json"),
	Hatchet:              CreateItemWeapon("./data/Hatchet.json"),
	Halberd:              CreateItemWeapon("./data/Halberd.json"),
	HandCrossbow:         CreateItemWeapon("./data/HandCrossbow.json"),
	HeaterShield:         CreateItemWeapon("./data/HeaterShield.json"),
	HorsemanAxe:          CreateItemWeapon("./data/HorsemanAxe.json"),
	KrisDagger:           CreateItemWeapon("./data/KrisDagger.json"),
	LaternShield:         CreateItemWeapon("./data/LaternShield.json"),
	Longbow:              CreateItemWeapon("./data/Longbow.json"),
	Longsword:            CreateItemWeapon("./data/Longsword.json"),
	MagicStaff:           CreateItemWeapon("./data/MagicStaff.json"),
	MorningStar:          CreateItemWeapon("./data/MorningStar.json"),
	Pavise:               CreateItemWeapon("./data/Pavise.json"),
	Quarterstaff:         CreateItemWeapon("./data/Quarterstaff.json"),
	Rapier:               CreateItemWeapon("./data/Rapier.json"),
	RecurveBow:           CreateItemWeapon("./data/RecurveBow.json"),
	RoundShield:          CreateItemWeapon("./data/RoundShield.json"),
	Spear:                CreateItemWeapon("./data/Spear.json"),
	Spellbook:            CreateItemWeapon("./data/Spellbook.json"),
	StilletoDagger:       CreateItemWeapon("./data/StilletoDagger.json"),
	SurvivalBow:          CreateItemWeapon("./data/SurvivalBow.json"),
	ThrowingKnife:        CreateItemWeapon("./data/ThrowingKnife.json"),
	VikingSword:          CreateItemWeapon("./data/VikingSword.json"),
	WarHammer:            CreateItemWeapon("./data/WarHammer.json"),
	WarMaul:              CreateItemWeapon("./data/WarMaul.json"),
	WindlassCrossbow:     CreateItemWeapon("./data/WindlassCrossbow.json"),
	Zweihander:           CreateItemWeapon("./data/Zweihander.json"),
	PaddedTunic:          CreateItemArmor("./data/PaddedTunic.json"),
}

var Items = services.List_Items{
	ItemsArmor: []*models.Item_Armor{
		&item.Armet,
		&item.CrusaderHelm,
		&item.Doublet,
		&item.RivetedGloves,
		&item.LooseTrousers,
		&item.LightfootBoots,
		&item.RadiantCloak,
		&item.AdventurerCloak,
		&item.BarbutaHelm,
		&item.ChapelDeFer,
		&item.OccultistPants,
		&item.AdventurerBoots,
		&item.ArcaneHood,
		&item.CeremonialHeaddress,
		&item.Chaperon,
		&item.Coif,
		&item.DarkgroveHood,
		&item.ElkwoodCrown,
		&item.FeatheredHat,
		&item.ForestHood,
		&item.Gjermundbu,
		&item.GreatHelm,
		&item.Hounskull,
		&item.KettleHat,
		&item.LeatherBonnet,
		&item.LeatherCap,
		&item.NormanNasalHelm,
		&item.OpenSallet,
		&item.RangerHood,
		&item.RogueCowl,
		&item.Sallet,
		&item.ShadowHood,
		&item.ShadowMask,
		&item.Spangenhelm,
		&item.StrawHat,
		&item.Topfhelm,
		&item.VikingHelm,
		&item.OccultistHood,
		&item.AdventurerTunic,
		&item.ArcaneGrab,
		&item.ArcaneGloves,
		&item.BardicPants,
		&item.BloodwovenGloves,
		&item.ChampionArmor,
		&item.CrusaderArmor,
		&item.BloodwovenRobe,
		&item.BuckledBoots,
		&item.ButtonedBoots,
		&item.ButtonedLeggings,
		&item.ClothPants,
		&item.CuffedBoots,
		&item.DarkCuirass,
		&item.DarkgroveRobe,
		&item.DarkleafBoots,
		&item.DarkLeatherLeggings,
		&item.DarkPlateArmor,
		&item.DashingBoots,
		&item.DreadHood,
		&item.ElkwoodGloves,
		&item.FineCuirass,
		&item.ForestBoots,
		&item.Frock,
		&item.GlovesOfUtility,
		&item.GrandBrigandine,
		&item.WandererAttire,
		&item.WatchmanCloak,
		&item.WizardHat,
		&item.WizardShoes,
		&item.HeavyBoots,
		&item.HeavyGambeson,
		&item.HeavyGauntlets,
		&item.HeavyLeggings,
		&item.HeavyLeatherLeggings,
		&item.LacedTurnshoe,
		&item.LeatherGloves,
		&item.LeatherLeggings,
		&item.LightAketon,
		&item.LightGauntlets,
		&item.LowBoots,
		&item.MarauderOutfit,
		&item.MercurialCloak,
		&item.MysticGloves,
		&item.MysticVestments,
		&item.NorthernFullTunic,
		&item.OccultistRobe,
		&item.OccultistTunic,
		&item.OldShoes,
		&item.Pourpoint,
		&item.TemplarArmor,
		&item.TatteredCloak,
		&item.SplendidCloak,
		&item.OccultistBoots,
		&item.PlateBoots,
		&item.VisoredSallet,
		&item.VisoredBarbutaHelm,
		&item.PaddedTunic,
	},
	ItemsWeapon: []*models.Item_Weapon{
		&item.ArmingSword,
		&item.Bardiche,
		&item.CastillonDagger,
		&item.Buckler,
		&item.CeremonialStaff,
		&item.Club,
		&item.Crossbow,
		&item.CrystalBall,
		&item.CrystalSword,
		&item.DoubleAxe,
		&item.Falchion,
		&item.FellinAxe,
		&item.FranciscaAxe,
		&item.Hatchet,
		&item.Halberd,
		&item.HandCrossbow,
		&item.HeaterShield,
		&item.HorsemanAxe,
		&item.KrisDagger,
		&item.LaternShield,
		&item.Longbow,
		&item.Longsword,
		&item.MagicStaff,
		&item.MorningStar,
		&item.Pavise,
		&item.Quarterstaff,
		&item.Rapier,
		&item.RecurveBow,
		&item.RoundShield,
		&item.Spear,
		&item.Spellbook,
		&item.StilletoDagger,
		&item.SurvivalBow,
		&item.ThrowingKnife,
		&item.VikingSword,
		&item.WarHammer,
		&item.WarMaul,
		&item.WindlassCrossbow,
		&item.Zweihander,
	},
	ItemsAccessory: []*models.Item_Accessory{
		&item.FoxPendant,
		&item.RingOfCourage,
		&item.BadgerPendant,
		&item.BearPendant,
		&item.FrostAmulet,
		&item.MonkeyPendant,
		&item.NecklaceOfPeace,
		&item.OwlPendant,
		&item.OxPendant,
		&item.PhoenixChoker,
		&item.RatPendant,
		&item.TorqOfSoul,
		&item.WindLocket,
		&item.FangsOfDeathNecklace,
		&item.RingOfFinesse,
		&item.RingOfQuickness,
		&item.RingOfSurvival,
		&item.RingOfVitality,
		&item.RingOfWisdom,
		&item.RingOfResolve,
	},
}
