package models

type Attributes struct {
	Strenght        []float64
	Vigor           []float32
	Agility         []float32
	Dexterity       []float32
	Will            []float32
	Knowledge       []float32
	Resourcefulness []float32
}

type PhysicalDamage struct {
	TruePhyisicalDamage    []float32
	PhysicalPowerBonus     []float32
	PhysicalPower          []float32
	AdditionalWeaponDamage []float32
	PhysicalDamage         []float32
	ArmorPenetration       []float32
}

type MagicalDamage struct {
	MagicalPowerBonus []float32
	MagicalPower      []float32
	MagicalDamage     []float32
	TrueMagicalDamage []float32
	MagicPenetration  []float32
}

type Reductions struct {
	ArmorRating             []float32
	PhysicalDamageReduction []float32
	ProjectileReduction     []float32
	MagicalDamageReduction  []float32
	MagicResistance         []float32
	CooldownReduction       []float32
}

type Actions struct {
	ActionSpeed             []float32
	RegularInteractionSpeed []float32
	MagicalInteractionSpeed []float32
	SpellCastingSpeed       []float32
	MoveSpeed               []float32
	MoveSpeedBonus          []float32
}

type Health struct {
	MaxHealthAdd    []float32
	MaxHealthBonus  []float32
	PhysicalHealing []float32
	MagicalHealing  []float32
}
type Statuses struct {
	BuffDurationBonus []float32
	DebuffDuration    []float32
}

type Memory struct {
	MemoryCapacityAdd   []float32
	MemoryCapacityBonus []float32
}

type Misc struct {
	Luck []float32
}

type Enchantmentx struct {
	Base      Attributes
	Physical  PhysicalDamage
	Magical   MagicalDamage
	Reduction Reductions
	Action    Actions
	Health    Health
	Status    Statuses
	Memory    Memory
	Misc      Misc
}

type Enchanmentcat struct {
	Attributes map[string][]float32
	Others     map[string][]float32
}

type Enchantment struct {
	Helmet          map[string][]float32
	Chest           map[string][]float32
	Gloves          map[string][]float32
	Pants           map[string][]float32
	Boots           map[string][]float32
	Cloak           map[string][]float32
	Necklace        map[string][]float32
	Ring            map[string][]float32
	WeaponOneHand   map[string][]float32
	ShieldOneHand   map[string][]float32
	ShieldTwoHand   map[string][]float32
	PhysicalTwoHand map[string][]float32
	HybridTwoHand   map[string][]float32
	MagicalTwoHand  map[string][]float32
}

var Enchantments = Enchantment{
	// Armor
	Helmet: map[string][]float32{
		"UndeadDamageReduction":   {1, 2},
		"MagicalPower":            {1, 1},
		"DemonDamageBonus":        {1, 2},
		"ArmorRating":             {3, 6},
		"ActionSpeed":             {0.6, 1.2},
		"MaxHealthAdd":            {1, 3},
		"MemoryCapacityBonus":     {1.5, 3},
		"Knowledge":               {1, 2},
		"RegularInteractionSpeed": {1, 2},
		"Resourcefulness":         {1, 2},
		"PhysicalDamageReduction": {0.5, 1},
		"Luck":                    {15, 30},
		"CooldownReduction":       {0.7, 1.5},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"MagicalDamageReduction":  {0.5, 1},
		"Vigor":                   {1, 2},
		"MagicalHealing":          {1, 1},
		"MagicResistance":         {3, 6},
		"DemonDamageReduction":    {1, 2},
		"SpellCastingSpeed":       {1, 2},
		"ProjectileReduction":     {0.7, 1.5},
		"BuffDurationBonus":       {0.7, 1.5},
		"Will":                    {1, 2},
		"ArmorPenetration":        {1, 2},
		"PhysicalHealing":         {1, 1},
		"MagicPenetration":        {1, 2},
		"Dexterity":               {1, 2},
		"MagicalDamageAdd":        {1, 1},
		"HeadshotDamage":          {1, 2},
		"MagicalInteractionSpeed": {1, 2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"Agility":                 {1, 2},
		"MaxHealthBonus":          {1, 2},
		"MemoryCapacityAdd":       {1, 2},
		"DebuffDurationBonus":     {0.7, 1.5},
		"PhysicalPower":           {1, 1},
		"UndeadDamageBonus":       {1, 2},
		"Strength":                {1, 2},
	},
	Chest: map[string][]float32{
		"PhysicalPower":           {1, 2},
		"DemonDamageReduction":    {1.5, 3},
		"MemoryCapacityAdd":       {2, 4},
		"Dexterity":               {1, 3},
		"Will":                    {1, 3},
		"CooldownReduction":       {1, 2},
		"Vigor":                   {1, 3},
		"MaxHealthBonus":          {1.5, 3},
		"MagicalPower":            {1, 2},
		"PhysicalHealing":         {1, 1},
		"ProjectileReduction":     {1, 2},
		"MemoryCapacityBonus":     {2.2, 4.5},
		"Strength":                {1, 3},
		"MagicalHealing":          {1, 1},
		"ArmorRating":             {5, 10},
		"MagicResistance":         {5, 10},
		"ActionSpeed":             {0.9, 1.8},
		"HeadshotDamage":          {1.5, 3},
		"UndeadDamageReduction":   {1.5, 3},
		"PhysicalPowerBonus":      {0.9, 1.8},
		"MagicalInteractionSpeed": {1.5, 3},
		"MagicPenetration":        {1.5, 3},
		"Agility":                 {1, 3},
		"Knowledge":               {1, 3},
		"MagicalPowerBonus":       {0.7, 1.8},
		"RegularInteractionSpeed": {1.5, 3},
		"DebuffDurationBonus":     {1, 2},
		"MaxHealthAdd":            {2, 4},
		"Luck":                    {22, 45},
		"SpellCastingSpeed":       {1.2, 2.5},
		"DemonDamageBonus":        {1.5, 3},
		"PhysicalDamageReduction": {0.7, 1.5},
		"UndeadDamageBonus":       {1.5, 3},
		"ArmorPenetration":        {1.5, 3},
		"MagicalDamageReduction":  {0.7, 1.5},
		"Resourcefulness":         {1, 3},
		"BuffDurationBonus":       {1, 2},
	},
	Gloves: map[string][]float32{
		"Vigor":                   {1, 2},
		"Luck":                    {15, 30},
		"DemonDamageReduction":    {1, 2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"MemoryCapacityBonus":     {1.5, 3},
		"Agility":                 {1, 2},
		"DemonDamageBonus":        {1, 2},
		"AdditionalWeaponDamage":  {1, 1},
		"Resourcefulness":         {1, 2},
		"UndeadDamageReduction":   {1, 2},
		"DebuffDurationBonus":     {0.7, 1.5},
		"PhysicalDamageReduction": {0.5, 1},
		"PhysicalHealing":         {1, 1},
		"SpellCastingSpeed":       {1, 2},
		"CooldownReduction":       {0.7, 1.5},
		"MagicPenetration":        {1, 2},
		"Knowledge":               {1, 2},
		"BuffDurationBonus":       {0.7, 1.5},
		"ArmorRating":             {3, 6},
		"UndeadDamageBonus":       {1, 2},
		"MagicalHealing":          {1, 1},
		"MagicalPower":            {1, 1},
		"Will":                    {1, 2},
		"MagicalInteractionSpeed": {1, 2},
		"MemoryCapacityAdd":       {1, 2},
		"RegularInteractionSpeed": {1, 2},
		"Dexterity":               {1, 2},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"ArmorPenetration":        {1, 2},
		"Strength":                {1, 2},
		"PhysicalPower":           {1, 1},
		"HeadshotDamage":          {1, 2},
		"MaxHealthBonus":          {1, 2},
		"MagicResistance":         {3, 6},
		"ActionSpeed":             {0.6, 1.2},
		"MaxHealthAdd":            {1, 3},
		"MagicalDamageReduction":  {0.5, 1},
		"ProjectileReduction":     {0.7, 1.5},
	},
	Pants: map[string][]float32{
		"MagicalDamageReduction":  {0.7, 1.5},
		"MagicPenetration":        {1.5, 3},
		"UndeadDamageBonus":       {1.5, 3},
		"SpellCastingSpeed":       {1.2, 2.5},
		"MemoryCapacityBonus":     {2.2, 4.5},
		"MagicalHealing":          {1, 1},
		"DemonDamageBonus":        {1.5, 3},
		"Knowledge":               {1, 3},
		"Dexterity":               {1, 3},
		"Strength":                {1, 3},
		"DebuffDurationBonus":     {1, 2},
		"MagicResistance":         {5, 10},
		"PhysicalDamageReduction": {0.7, 1.5},
		"ArmorPenetration":        {1.5, 3},
		"Agility":                 {1, 3},
		"Will":                    {1, 3},
		"MaxHealthBonus":          {1.5, 3},
		"RegularInteractionSpeed": {1.5, 3},
		"HeadshotDamage":          {1.5, 3},
		"Luck":                    {22, 45},
		"Vigor":                   {1, 3},
		"MemoryCapacityAdd":       {2, 4},
		"ArmorRating":             {5, 10},
		"ActionSpeed":             {0.9, 1.8},
		"MaxHealthAdd":            {2, 4},
		"PhysicalPowerBonus":      {0.9, 1.8},
		"PhysicalHealing":         {1, 1},
		"MagicalPower":            {1, 2},
		"PhysicalPower":           {1, 2},
		"DemonDamageReduction":    {1.5, 3},
		"ProjectileReduction":     {1, 2},
		"Resourcefulness":         {1, 3},
		"UndeadDamageReduction":   {1.5, 3},
		"BuffDurationBonus":       {1, 2},
		"MagicalInteractionSpeed": {1.5, 3},
		"MagicalPowerBonus":       {0.7, 1.8},
		"CooldownReduction":       {1, 2},
	},
	Boots: map[string][]float32{
		"PhysicalDamageReduction": {0.5, 1},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"DemonDamageBonus":        {1, 2},
		"HeadshotDamage":          {1, 2},
		"MoveSpeed":               {1, 5},
		"Luck":                    {15, 30},
		"MemoryCapacityBonus":     {1.5, 3},
		"MaxHealthBonus":          {1, 2},
		"MemoryCapacityAdd":       {1, 2},
		"Resourcefulness":         {1, 2},
		"UndeadDamageReduction":   {1, 2},
		"MagicResistance":         {3, 6},
		"UndeadDamageBonus":       {1, 2},
		"MagicPenetration":        {1, 2},
		"Knowledge":               {1, 2},
		"DebuffDurationBonus":     {0.7, 1.5},
		"MagicalPower":            {1, 1},
		"DemonDamageReduction":    {1, 2},
		"MagicalInteractionSpeed": {1, 2},
		"SpellCastingSpeed":       {1, 2},
		"CooldownReduction":       {0.7, 1.5},
		"RegularInteractionSpeed": {1, 2},
		"Dexterity":               {1, 2},
		"ArmorPenetration":        {1, 2},
		"Vigor":                   {1, 2},
		"MoveSpeedBonus":          {0.3, 1.5},
		"Will":                    {1, 2},
		"ActionSpeed":             {0.6, 1.2},
		"MaxHealthAdd":            {1, 3},
		"PhysicalHealing":         {1, 1},
		"ProjectileReduction":     {0.7, 1.5},
		"Agility":                 {1, 2},
		"PhysicalPower":           {1, 1},
		"MagicalDamageReduction":  {0.5, 1},
		"Strength":                {1, 2},
		"MagicalHealing":          {1, 1},
		"BuffDurationBonus":       {0.7, 1.5},
		"ArmorRating":             {3, 6},
	},
	Cloak: map[string][]float32{
		"ArmorPenetration":        {1, 2},
		"DemonDamageReduction":    {1, 2},
		"ProjectileReduction":     {0.7, 1.5},
		"MagicalHealing":          {1, 1},
		"Resourcefulness":         {1, 2},
		"BuffDurationBonus":       {0.7, 1.5},
		"PhysicalHealing":         {1, 1},
		"MemoryCapacityAdd":       {1, 2},
		"UndeadDamageReduction":   {1, 2},
		"DebuffDurationBonus":     {0.7, 1.5},
		"MagicalDamageAdd":        {1, 1},
		"PhysicalPower":           {1, 1},
		"HeadshotDamage":          {1, 2},
		"MagicPenetration":        {1, 2},
		"Vigor":                   {1, 2},
		"Knowledge":               {1, 2},
		"ArmorRating":             {3, 6},
		"ActionSpeed":             {0.6, 1.2},
		"Luck":                    {15, 30},
		"DemonDamageBonus":        {1, 2},
		"MaxHealthBonus":          {1, 2},
		"MagicalPower":            {1, 1},
		"Strength":                {1, 2},
		"Agility":                 {1, 2},
		"Dexterity":               {1, 2},
		"MagicResistance":         {3, 6},
		"PhysicalDamageReduction": {0.5, 1},
		"UndeadDamageBonus":       {1, 2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"CooldownReduction":       {0.7, 1.5},
		"MemoryCapacityBonus":     {1.5, 3},
		"RegularInteractionSpeed": {1, 2},
		"AdditionalWeaponDamage":  {1, 1},
		"Will":                    {1, 2},
		"MagicalInteractionSpeed": {1, 2},
		"SpellCastingSpeed":       {1, 2},
		"MagicalDamageReduction":  {0.5, 1},
		"MaxHealthAdd":            {1, 3},
		"PhysicalPowerBonus":      {0.6, 1.2},
	},

	// Accessories
	Necklace: map[string][]float32{
		"AdditionalWeaponDamage":  {1, 1},
		"PhysicalHealing":         {1, 1},
		"ActionSpeed":             {0.9, 1.8},
		"HeadshotDamage":          {1.5, 3},
		"ArmorPenetration":        {1.5, 3},
		"Vigor":                   {1, 3},
		"UndeadDamageBonus":       {1.5, 3},
		"MagicalPowerBonus":       {0.7, 1.8},
		"SpellCastingSpeed":       {1.2, 2.5},
		"MagicalDamageReduction":  {0.7, 1.5},
		"MagicPenetration":        {1.5, 3},
		"Strength":                {1, 3},
		"Knowledge":               {1, 3},
		"Will":                    {1, 3},
		"DemonDamageReduction":    {1.5, 3},
		"MagicalHealing":          {1, 1},
		"Resourcefulness":         {1, 3},
		"UndeadDamageReduction":   {1.5, 3},
		"ArmorRating":             {5, 10},
		"AllAttributes":           {1, 1},
		"MaxHealthBonus":          {1.5, 3},
		"MemoryCapacityAdd":       {2, 4},
		"RegularInteractionSpeed": {1.5, 3},
		"MagicResistance":         {5, 10},
		"PhysicalDamageReduction": {0.7, 1.5},
		"MagicalInteractionSpeed": {1.5, 3},
		"DemonDamageBonus":        {1.5, 3},
		"BuffDurationBonus":       {1, 2},
		"MagicalPower":            {1, 2},
		"PhysicalPower":           {1, 2},
		"MaxHealthAdd":            {2, 4},
		"ProjectileReduction":     {1, 2},
		"Dexterity":               {1, 3},
		"DebuffDurationBonus":     {1, 2},
		"PhysicalPowerBonus":      {0.9, 1.8},
		"Luck":                    {22, 45},
		"CooldownReduction":       {1, 2},
		"MemoryCapacityBonus":     {2.2, 4.5},
		"Agility":                 {1, 3},
		"MagicalDamageAdd":        {1, 1},
	},
	Ring: map[string][]float32{
		"UndeadDamageReduction":   {1, 2},
		"MagicPenetration":        {1, 2},
		"DemonDamageBonus":        {1, 2},
		"MemoryCapacityAdd":       {1, 2},
		"BuffDurationBonus":       {0.7, 1.5},
		"MagicalDamageAdd":        {1, 1},
		"Will":                    {1, 2},
		"MagicalHealing":          {1, 1},
		"Dexterity":               {1, 2},
		"ArmorRating":             {3, 6},
		"MagicResistance":         {3, 6},
		"MagicalInteractionSpeed": {1, 2},
		"ProjectileReduction":     {0.7, 1.5},
		"PhysicalDamageReduction": {0.5, 1},
		"ActionSpeed":             {0.6, 1.2},
		"HeadshotDamage":          {1, 2},
		"UndeadDamageBonus":       {1, 2},
		"ArmorPenetration":        {1, 2},
		"PhysicalHealing":         {1, 1},
		"SpellCastingSpeed":       {1, 2},
		"DebuffDurationBonus":     {0.7, 1.5},
		"Vigor":                   {1, 2},
		"PhysicalPower":           {1, 1},
		"Luck":                    {15, 30},
		"AllAttributes":           {1, 1},
		"MagicalDamageReduction":  {0.5, 1},
		"MemoryCapacityBonus":     {1.5, 3},
		"Agility":                 {1, 2},
		"Resourcefulness":         {1, 2},
		"DemonDamageReduction":    {1, 2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"Strength":                {1, 2},
		"Knowledge":               {1, 2},
		"MaxHealthAdd":            {1, 3},
		"MagicalPower":            {1, 1},
		"AdditionalWeaponDamage":  {1, 1},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"CooldownReduction":       {0.7, 1.5},
		"MaxHealthBonus":          {1, 2},
		"RegularInteractionSpeed": {1, 2},
	},

	// Weapons
	WeaponOneHand: map[string][]float32{
		"AdditionalWeaponDamage":  {1, 1},
		"CooldownReduction":       {0.7, 1.5},
		"MagicPenetration":        {1, 2},
		"MemoryCapacityBonus":     {1.5, 3},
		"Vigor":                   {1, 1},
		"ArmorRating":             {3, 6},
		"ActionSpeed":             {0.6, 1.2},
		"UndeadDamageBonus":       {1, 2},
		"MagicalDamageReduction":  {0.5, 1},
		"Agility":                 {1, 1},
		"DebuffDurationBonus":     {0.7, 1.5},
		"Luck":                    {15, 30},
		"Strength":                {1, 1},
		"MaxHealthBonus":          {0.7, 1.5},
		"RegularInteractionSpeed": {1, 2},
		"HeadshotDamage":          {1, 2},
		"ArmorPenetration":        {1, 2},
		"MemoryCapacityAdd":       {1, 2},
		"MaxHealthAdd":            {1, 2},
		"ProjectileReduction":     {0.7, 1.5},
		"UndeadDamageReduction":   {1, 2},
		"MagicResistance":         {3, 6},
		"PhysicalDamageReduction": {0.5, 1},
		"PhysicalPower":           {1, 1},
		"Will":                    {1, 1},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"Resourcefulness":         {1, 1},
		"MagicalInteractionSpeed": {1, 2},
		"MagicalHealing":          {1, 1},
		"DemonDamageBonus":        {1, 2},
		"Dexterity":               {1, 1},
		"BuffDurationBonus":       {0.7, 1.5},
		"DemonDamageReduction":    {1, 2},
		"PhysicalHealing":         {1, 1},
		"SpellCastingSpeed":       {1, 2},
		"Knowledge":               {1, 1},
		"MagicalPower":            {1, 1},
	},
	ShieldOneHand: map[string][]float32{
		"MagicalPower":            {1, 1},
		"MaxHealthAdd":            {1, 2},
		"UndeadDamageBonus":       {1, 2},
		"MagicalPowerBonus":       {0.5, 1.2},
		"SpellCastingSpeed":       {1, 2},
		"PhysicalDamageReduction": {0.5, 1},
		"Luck":                    {15, 30},
		"MagicalInteractionSpeed": {1, 2},
		"MemoryCapacityBonus":     {1.5, 3},
		"Will":                    {1, 1},
		"PhysicalHealing":         {1, 1},
		"CooldownReduction":       {0.7, 1.5},
		"Strength":                {1, 1},
		"Knowledge":               {1, 1},
		"MaxHealthBonus":          {0.7, 1.5},
		"BuffDurationBonus":       {0.7, 1.5},
		"ArmorRating":             {3, 6},
		"MagicResistance":         {3, 6},
		"HeadshotDamage":          {1, 2},
		"ProjectileReduction":     {0.7, 1.5},
		"Agility":                 {1, 1},
		"DemonDamageBonus":        {1, 2},
		"AdditionalWeaponDamage":  {1, 1},
		"PhysicalPower":           {1, 1},
		"ActionSpeed":             {0.6, 1.2},
		"DemonDamageReduction":    {1, 2},
		"RegularInteractionSpeed": {1, 2},
		"Resourcefulness":         {1, 1},
		"DebuffDurationBonus":     {0.7, 1.5},
		"PhysicalPowerBonus":      {0.6, 1.2},
		"MagicalHealing":          {1, 1},
		"MemoryCapacityAdd":       {1, 2},
		"Dexterity":               {1, 1},
		"UndeadDamageReduction":   {1, 2},
		"ArmorPenetration":        {1, 2},
		"MagicalDamageReduction":  {0.5, 1},
		"MagicPenetration":        {1, 2},
		"Vigor":                   {1, 1},
	},
	ShieldTwoHand: map[string][]float32{
		"HeadshotDamage":          {2, 4},
		"Luck":                    {30, 60},
		"CooldownReduction":       {1.5, 3},
		"RegularInteractionSpeed": {2, 4},
		"PhysicalDamageReduction": {1, 2},
		"ArmorPenetration":        {2, 4},
		"PhysicalHealing":         {1, 2},
		"SpellCastingSpeed":       {2, 4},
		"Strength":                {1, 2},
		"Vigor":                   {1, 2},
		"MaxHealthBonus":          {1.5, 3},
		"ArmorRating":             {6, 12},
		"PhysicalPowerBonus":      {1.2, 2.4},
		"UndeadDamageBonus":       {2, 4},
		"MagicalInteractionSpeed": {2, 4},
		"MagicalPowerBonus":       {1.2, 2.4},
		"Knowledge":               {1, 2},
		"MagicalDamageReduction":  {1, 2},
		"MagicalHealing":          {1, 2},
		"Dexterity":               {1, 2},
		"Resourcefulness":         {1, 2},
		"AdditionalWeaponDamage":  {1, 2},
		"PhysicalPower":           {1, 2},
		"Will":                    {1, 2},
		"MemoryCapacityBonus":     {3, 6},
		"MemoryCapacityAdd":       {2, 4},
		"UndeadDamageReduction":   {2, 4},
		"BuffDurationBonus":       {1.5, 3},
		"DebuffDurationBonus":     {1.5, 3},
		"MagicResistance":         {6, 12},
		"ProjectileReduction":     {2, 4},
		"Agility":                 {1, 2},
		"DemonDamageBonus":        {2, 4},
		"DemonDamageReduction":    {2, 4},
		"MagicPenetration":        {2, 4},
		"MaxHealthAdd":            {2, 4},
		"MagicalPower":            {1, 2},
		"ActionSpeed":             {1.2, 2.4},
	},
	PhysicalTwoHand: map[string][]float32{
		"MagicResistance":         {6, 12},
		"PhysicalDamageReduction": {1, 2},
		"CooldownReduction":       {1.5, 3},
		"Knowledge":               {1, 2},
		"RegularInteractionSpeed": {2, 4},
		"MaxHealthBonus":          {1.5, 3},
		"DemonDamageBonus":        {2, 4},
		"UndeadDamageBonus":       {2, 4},
		"ArmorPenetration":        {2, 4},
		"ArmorRating":             {6, 12},
		"HeadshotDamage":          {2, 4},
		"Luck":                    {30, 60},
		"Resourcefulness":         {1, 2},
		"BuffDurationBonus":       {1.5, 3},
		"DebuffDurationBonus":     {1.5, 3},
		"DemonDamageReduction":    {2, 4},
		"PhysicalPower":           {1, 2},
		"MaxHealthAdd":            {2, 4},
		"SpellCastingSpeed":       {2, 4},
		"MemoryCapacityAdd":       {2, 4},
		"MagicalDamageReduction":  {1, 2},
		"ProjectileReduction":     {2, 4},
		"MagicalHealing":          {1, 2},
		"Agility":                 {1, 2},
		"Dexterity":               {1, 2},
		"UndeadDamageReduction":   {2, 4},
		"AdditionalWeaponDamage":  {1, 2},
		"ActionSpeed":             {1.2, 2.4},
		"PhysicalHealing":         {1, 2},
		"MemoryCapacityBonus":     {3, 6},
		"Vigor":                   {1, 2},
		"MagicalPower":            {1, 2},
		"Will":                    {1, 2},
		"PhysicalPowerBonus":      {1.2, 2.4},
		"MagicalInteractionSpeed": {2, 4},
		"MagicalPowerBonus":       {1.2, 2.4},
		"MagicPenetration":        {2, 4},
		"Strength":                {1, 2},
	},
	HybridTwoHand: map[string][]float32{
		"Dexterity":               {1, 2},
		"MaxHealthAdd":            {2, 4},
		"Luck":                    {30, 60},
		"DemonDamageReduction":    {2, 4},
		"MaxHealthBonus":          {1.5, 3},
		"UndeadDamageReduction":   {2, 4},
		"MagicalPower":            {1, 2},
		"AdditionalWeaponDamage":  {1, 2},
		"MemoryCapacityBonus":     {3, 6},
		"Strength":                {1, 2},
		"Vigor":                   {1, 2},
		"Knowledge":               {1, 2},
		"RegularInteractionSpeed": {2, 4},
		"DebuffDurationBonus":     {1.5, 3},
		"ArmorRating":             {6, 12},
		"ActionSpeed":             {1.2, 2.4},
		"ArmorPenetration":        {2, 4},
		"MagicalInteractionSpeed": {2, 4},
		"CooldownReduction":       {1.5, 3},
		"Resourcefulness":         {1, 2},
		"PhysicalPower":           {1, 2},
		"Will":                    {1, 2},
		"PhysicalPowerBonus":      {1.2, 2.4},
		"PhysicalHealing":         {1, 2},
		"MagicalHealing":          {1, 2},
		"DemonDamageBonus":        {2, 4},
		"MagicalPowerBonus":       {1.2, 2.4},
		"MagicPenetration":        {2, 4},
		"Agility":                 {1, 2},
		"PhysicalDamageReduction": {1, 2},
		"UndeadDamageBonus":       {2, 4},
		"MagicalDamageReduction":  {1, 2},
		"BuffDurationBonus":       {1.5, 3},
		"MagicResistance":         {6, 12},
		"HeadshotDamage":          {2, 4},
		"SpellCastingSpeed":       {2, 4},
		"ProjectileReduction":     {2, 4},
		"MemoryCapacityAdd":       {2, 4},
	},
	MagicalTwoHand: map[string][]float32{
		"Vigor":                   {1, 2},
		"MagicResistance":         {6, 12},
		"AdditionalWeaponDamage":  {1, 2},
		"HeadshotDamage":          {2, 4},
		"PhysicalPowerBonus":      {1.2, 2.4},
		"UndeadDamageBonus":       {2, 4},
		"MagicalDamageReduction":  {1, 2},
		"Resourcefulness":         {1, 2},
		"ArmorRating":             {6, 12},
		"Agility":                 {1, 2},
		"DemonDamageBonus":        {2, 4},
		"Knowledge":               {1, 2},
		"Dexterity":               {1, 2},
		"BuffDurationBonus":       {1.5, 3},
		"DebuffDurationBonus":     {1.5, 3},
		"PhysicalDamageReduction": {1, 2},
		"PhysicalPower":           {1, 2},
		"MaxHealthAdd":            {2, 4},
		"MagicalHealing":          {1, 2},
		"Will":                    {1, 2},
		"MagicPenetration":        {2, 4},
		"MemoryCapacityAdd":       {2, 4},
		"PhysicalHealing":         {1, 2},
		"SpellCastingSpeed":       {2, 4},
		"ProjectileReduction":     {2, 4},
		"UndeadDamageReduction":   {2, 4},
		"ActionSpeed":             {1.2, 2.4},
		"Luck":                    {30, 60},
		"DemonDamageReduction":    {2, 4},
		"MagicalInteractionSpeed": {2, 4},
		"MemoryCapacityBonus":     {3, 6},
		"MagicalPowerBonus":       {1.2, 2.4},
		"MaxHealthBonus":          {1.5, 3},
		"RegularInteractionSpeed": {2, 4},
		"MagicalPower":            {1, 2},
		"ArmorPenetration":        {2, 4},
		"CooldownReduction":       {1.5, 3},
		"Strength":                {1, 2},
	},
}
